#!/usr/bin/env python3
import rospy
import time
from geometry_msgs.msg import Twist
import pygame
import json, os

LEFT, RIGHT, UP, DOWN = False, False, False, False
pygame.init()
joysticks = []
for i in range(pygame.joystick.get_count()):
    joysticks.append(pygame.joystick.Joystick(i))
for joystick in joysticks:
    joystick.init()
#cwd = os.getcwd()     this fuction returns the current working
path = "/home/dhruv/mip_junior_300/src/mip_junior_300/src"
#cwd = os.getcwd()     this fuction returns the current working directory in which this file is being RAN.
#print(cwd)
with open(os.path.join(path, "ps3_keys.json"), 'r+') as file:
    button_keys = json.load(file)
analog_keys = {0:0, 1:0, 2:0, 3:0, 4:-1, 5: -1 }
rospy.init_node('custom_talker', anonymous=True)
pub = rospy.Publisher('/manipulator', Twist,queue_size = 10)

while not rospy.is_shutdown():
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN:
            pass
        msg = Twist()
        if event.type == pygame.JOYAXISMOTION:
            analog_keys[event.axis] = event.value
            msg.linear.x= -200*analog_keys[1]
            msg.linear.y = -200*analog_keys[4]
            rospy.loginfo(msg)
            pub.publish(msg)
    time.sleep(0.01)
    