// Generated by gencpp from file custom_msg/g2g_x_z.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_G2G_X_Z_H
#define CUSTOM_MSG_MESSAGE_G2G_X_Z_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg
{
template <class ContainerAllocator>
struct g2g_x_z_
{
  typedef g2g_x_z_<ContainerAllocator> Type;

  g2g_x_z_()
    : x(0.0)
    , z(0.0)  {
    }
  g2g_x_z_(const ContainerAllocator& _alloc)
    : x(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::custom_msg::g2g_x_z_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::g2g_x_z_<ContainerAllocator> const> ConstPtr;

}; // struct g2g_x_z_

typedef ::custom_msg::g2g_x_z_<std::allocator<void> > g2g_x_z;

typedef boost::shared_ptr< ::custom_msg::g2g_x_z > g2g_x_zPtr;
typedef boost::shared_ptr< ::custom_msg::g2g_x_z const> g2g_x_zConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::g2g_x_z_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::g2g_x_z_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg::g2g_x_z_<ContainerAllocator1> & lhs, const ::custom_msg::g2g_x_z_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg::g2g_x_z_<ContainerAllocator1> & lhs, const ::custom_msg::g2g_x_z_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg::g2g_x_z_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::g2g_x_z_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::g2g_x_z_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::g2g_x_z_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::g2g_x_z_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::g2g_x_z_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::g2g_x_z_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d990ebeae1ee5ba6990ba82cc74e4c5";
  }

  static const char* value(const ::custom_msg::g2g_x_z_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d990ebeae1ee5baULL;
  static const uint64_t static_value2 = 0x6990ba82cc74e4c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::g2g_x_z_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/g2g_x_z";
  }

  static const char* value(const ::custom_msg::g2g_x_z_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::g2g_x_z_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 z\n"
"\n"
;
  }

  static const char* value(const ::custom_msg::g2g_x_z_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::g2g_x_z_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct g2g_x_z_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::g2g_x_z_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::g2g_x_z_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_G2G_X_Z_H
