// Generated by gencpp from file custom_msg/lat_long_msg.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_LAT_LONG_MSG_H
#define CUSTOM_MSG_MESSAGE_LAT_LONG_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg
{
template <class ContainerAllocator>
struct lat_long_msg_
{
  typedef lat_long_msg_<ContainerAllocator> Type;

  lat_long_msg_()
    : lat(0.0)
    , long(0.0)  {
    }
  lat_long_msg_(const ContainerAllocator& _alloc)
    : lat(0.0)
    , long(0.0)  {
  (void)_alloc;
    }



   typedef float _lat_type;
  _lat_type lat;

   typedef float _long_type;
  _long_type long;





  typedef boost::shared_ptr< ::custom_msg::lat_long_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::lat_long_msg_<ContainerAllocator> const> ConstPtr;

}; // struct lat_long_msg_

typedef ::custom_msg::lat_long_msg_<std::allocator<void> > lat_long_msg;

typedef boost::shared_ptr< ::custom_msg::lat_long_msg > lat_long_msgPtr;
typedef boost::shared_ptr< ::custom_msg::lat_long_msg const> lat_long_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::lat_long_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::lat_long_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg::lat_long_msg_<ContainerAllocator1> & lhs, const ::custom_msg::lat_long_msg_<ContainerAllocator2> & rhs)
{
  return lhs.lat == rhs.lat &&
    lhs.long == rhs.long;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg::lat_long_msg_<ContainerAllocator1> & lhs, const ::custom_msg::lat_long_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg::lat_long_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::lat_long_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::lat_long_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::lat_long_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::lat_long_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::lat_long_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::lat_long_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72e4d8aabf891137eea8ff409e1fa1a8";
  }

  static const char* value(const ::custom_msg::lat_long_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72e4d8aabf891137ULL;
  static const uint64_t static_value2 = 0xeea8ff409e1fa1a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::lat_long_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/lat_long_msg";
  }

  static const char* value(const ::custom_msg::lat_long_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::lat_long_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 lat\n"
"float32 long\n"
;
  }

  static const char* value(const ::custom_msg::lat_long_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::lat_long_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat);
      stream.next(m.long);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lat_long_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::lat_long_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::lat_long_msg_<ContainerAllocator>& v)
  {
    s << indent << "lat: ";
    Printer<float>::stream(s, indent + "  ", v.lat);
    s << indent << "long: ";
    Printer<float>::stream(s, indent + "  ", v.long);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_LAT_LONG_MSG_H
